baseURL: https://yamate11.github.io/blog/
publishDir: docs
languageCode: en
title: "yamate11のブログ"
theme: "PaperMod"
paginate: 5
disqusShortname: "yamate11blog"

params:

    title: "yamate11のブログ"
    math: true
    DateFormat: "2006-01-02"
    env: "production"
    disableSpecial1stPost: true
    ShowPostNavLinks: true
    comments: true

    homeInfoParams:
        title: "yamate11のブログ"
        content: yamate11 の競技プログラミング用のblogです．
                 コメントは<a href="https://twitter.com/_yamate11">Twitter (_yamate11)</a>へお送りください．</br>
                 Links： <a href="https://atcoder.jp/users/yamate11">AtCoder (yamate11)</a> / 
                 <a href="https://codeforces.com/profile/yamate11">Codeforces (yamate11)</a> /
                 <a href="https://twitter.com/_yamate11">Twitter (_yamate11)</a>

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 10000000
        threshold: 0.2
#        ignoreLocation: true
#        ignoreFieldNorm: true
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    assets:
        disableHLJS: true

markup:
    highlight:
        codeFences: true
        guesssyntax: true
        # lineNos: true
        style: monokailight
    goldmark:
        renderer:
            unsafe: true
    
outputs:
    home:
        - HTML
        - RSS
        - JSON    # necessary for search

menu:
    main:
        - identifier: archives
          name: 記事一覧
          url: /archives/
          weight: 10
        - identifier: search
          name: 検索
          url: /search/
          weight: 20
        - identifier: about
          name: 筆者
          url: /pages/about/
          
#         - identifier: categories
#           name: categories
#           url: /categories/
#           weight: 30
#         - identifier: tags
#           name: tags
#           url: /tags/
#           weight: 40

taxonomies:
    category: categories
    tag: tags
    series: series

